# Generated by Django 3.1.1 on 2020-10-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20200919_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='Cap',
            field=models.CharField(default='', max_length=50, verbose_name='Капитализация'),
        ),
    ]
