# Generated by Django 2.2 on 2020-11-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_info_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='CapSort',
            field=models.FloatField(default=0, verbose_name='капитализация (сортировка)'),
        ),
        migrations.AddField(
            model_name='info',
            name='PriceSort',
            field=models.FloatField(default=0, verbose_name='цена (сортировка)'),
        ),
        migrations.AddField(
            model_name='info',
            name='div_year_Sort',
            field=models.FloatField(default=0, verbose_name='дивиденды в год (сортировка)'),
        ),
    ]
